### PR TITLE
Round generation dispatch log values

### PR DESCRIPTION
**Pull request by lilian-houdelet**

### CODE REVIEW

**Review by FranckLecuyer — CHANGES_REQUESTED** [review]

**Review by dbraquart — CHANGES_REQUESTED** [review]
code: ok but seemingly some reports are not rounded (cf activePowerSumByEnergySource calls - see https://github.com/gridsuite/network-modification-server/pull/392/commits/e243ec937e47e47fe2d07570dd0fb45919779fd9)
tests: dont we have to round the summary per region report too ?

Ex: 
Sum of generator active power setpoints in SOUTH region: **322.501256** MW (NUCLEAR: 0.0 MW, THERMAL: 0.0 MW, HYDRO: **322.501256** MW, WIND AND SOLAR...

**Comment by lilian-houdelet** [comment]
> code: ok but seemingly some reports are not rounded (cf activePowerSumByEnergySource calls - see [e243ec9](https://github.com/gridsuite/network-modification-server/commit/e243ec937e47e47fe2d07570dd0fb45919779fd9)) tests: dont we have to round the summary per region report too ?
> 
> Ex: Sum of generator active power setpoints in SOUTH region: **322.501256** MW (NUCLEAR: 0.0 MW, THERMAL: 0.0 MW, HYDRO: **322.501256** MW, WIND AND SOLAR...

Added in https://github.com/gridsuite/network-modification-server/pull/392 if I'm not wrong
I found one that is not rounded in both, I will add it

**Review by dbraquart — CHANGES_REQUESTED** [review]
code: ok but some reports are not rounded (cf activePowerSumByEnergySource calls - see as example [e243ec9](https://github.com/gridsuite/network-modification-server/commit/e243ec937e47e47fe2d07570dd0fb45919779fd9))
=> my PR https://github.com/gridsuite/network-modification-server/pull/392 is based on yours, so you have to make the change first

**Review by dbraquart — APPROVED** [review]
code: ok
tests: ok

**Pull request merged**
